### ISSUE TITLE
This doesn't seem to work with RN 0.54

### ISSUE THREAD

**Issue by wynch** [ds300/react-native-typescript-transformer#50]
When starting Metro, I get a `Cannot find module 'metro/src/transformer'` error.

**Comment by emin93** [comment]
It should also work with RN 0.54, I used it in my React Native TypeScript template.

If you want to see how I configured it, just run this in your terminal:
```
react-native init MyApp --template typescript
cd MyApp
node setup.js
```

**Comment by ds300** [comment]
Hi! I'm going to close this, since there doesn't seem to be any activity and I can't reproduce the problem. Let me know if it's still an issue for you!

**Comment by wynch** [comment]
Sorry for not coming back sooner on this !

I did try the Rect Native Typescript template, and managed to make it work.
In the end, I think it was related to my package.json and package-lock.json being out of sync : I deleted the lock file and did and nom install again, it worked !

Thanks !
